openapi: 3.0.0
info:
  title: Swagger Analyst Developer - OpenAPI 3.0
  description: |-
    Service created only practce, study.

    With service you manage a analyst how create, read, update and delete.
    
    The data are listed on table on front-end with angular basic.
  termsOfService: http://swagger.io/terms/
  contact:
    email: miguel.silva@mackenzista.com.br
  version: 0.0.1

tags:
  - name: "Analyst"
    description: "Manage Analyst"
    externalDocs:
      description: ""
      url: "http://swagger.io"


paths:

  /analyst/create:
    post:
      tags:
        - "Analyst"
      summary: "Add a new analyst to the internal talent"
      description: "Add a new analyst to the internal talent"
      operationId: addAnalyst
      requestBody:
        description: Create a new analyst in the internal talent
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalystDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystDTO'
        '405':
          description: Invalid input

  /analyst/{pId}:
    get:
      tags:
        - "Analyst"
      summary: Find Analyst by ID
      description: Returns a single Analyst
      operationId: getAnalystById
      parameters:
        - name: pId
          in: path
          description: pId of Analyst to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystDTO'
        '400':
          description: Invalid ID supplied
        '404':
          description: pId not found

  /analyst/all:
    get:
      tags:
        - "Analyst"
      summary: List all Analyst
      description: Returns a list of Analyst
      operationId: getAllAnalyst
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            application/json:   # One of media types
              schema:
                $ref: '#/components/schemas/AnalystDTO'
              example:
                - pId: 1
                  actuation: BACK
                  stack: JAVA
                - pId: 2
                  actuation: FRONT
                  stack: ANGULAR

  /analyst/{pId}/delete:
    get:
      tags:
        - "Analyst"
      summary: Delete Analyst by ID
      description: Delete a single Analyst
      operationId: deleteAnalystById
      parameters:
        - name: pId
          in: path
          description: pId of Analyst to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: pId not found

  /analyst/update:
    put:
      tags:
        - "Analyst"
      summary: Update an existing analyst
      description: Update an existing analyst by Id
      operationId: updateAnalyst
      requestBody:
        description: Update analyst in the internal talent
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalystDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystDTO'
        '400':
          description: Invalid ID supplied
        '404':
          description: Analyst not found
        '405':
          description: Validation exception

components:
  schemas:
    AnalystDTO:
      required:
        - pId
        - actuation
        - stack
      type: object
      properties:
        pId:
          type: integer
          format: int64
          example: 8
        actuation:
          type: string
          enum:
            - BACK
            - FRONT
            - BLANK
        stack:
          type: string
          enum:
            - JAVA
            - ANGULAR
            - DEVOPS
            - SECURITY_INFORMATION